version: "3.8"

services:
  get-data:
    build:
      dockerfile: ../Dockerfile
      context: get-data
    image: get-data
    env_file: .env
    environment:
      - STORAGE_ENVIRONMENT=s3
      - DATA_DIR=/data/raw
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src
        target: /src
      - type: bind
        source: ~/.aws
        target: /root/.aws

  infer-features:
    build:
      dockerfile: ../Dockerfile
      context: infer-features
    image: infer-features
    env_file: .env
    environment:
      - STORAGE_ENVIRONMENT=s3
      - DATA_DIR=/data/raw
    volumes:
      - type: bind
        source: ./data
        target: /data

  train-lsh-model:
    build:
      dockerfile: ../Dockerfile
      context: train-lsh-model
    image: train-lsh-model
    env_file: .env
    environment:
      - STORAGE_ENVIRONMENT=s3
      - DATA_DIR=/data/raw
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src
        target: /src

  infer-hashes:
    build:
      dockerfile: ../Dockerfile
      context: infer-hashes
    image: infer-hashes
    env_file: .env
    environment:
      - STORAGE_ENVIRONMENT=s3
      - DATA_DIR=/data/raw
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src
        target: /src
